export const demoCategories = [
  {
    id: "cat-electrical",
    name: "Electrical Components",
    slug: "electrical",
    description: "Essential electrical components for residential and commercial use",
    imageUrl: "/product-1.jpg",
  },
  {
    id: "cat-lighting",
    name: "Lighting Solutions",
    slug: "lighting", 
    description: "Modern LED lights, fixtures, and smart lighting systems",
    imageUrl: "/product-2.jpg",
  },
  {
    id: "cat-tools",
    name: "Tools & Equipment",
    slug: "tools",
    description: "Professional electrical tools and testing equipment",
    imageUrl: "/product-3.jpg",
  },
  {
    id: "cat-industrial",
    name: "Industrial Equipment",
    slug: "industrial",
    description: "Heavy-duty motors, transformers, and industrial machinery",
    imageUrl: "/product-4.jpg",
  },
  {
    id: "cat-automation",
    name: "Automation Systems",
    slug: "automation",
    description: "Smart controls, sensors, and automation solutions",
    imageUrl: "/product-1.jpg",
  },
  {
    id: "cat-cables",
    name: "Cables & Wiring",
    slug: "cables",
    description: "Power cables, data cables, and wire management systems",
    imageUrl: "/product-2.jpg",
  },
  {
    id: "cat-safety",
    name: "Safety Equipment", 
    slug: "safety",
    description: "Protective gear, emergency equipment, and safety tools",
    imageUrl: "/product-3.jpg",
  },
  {
    id: "cat-electronics",
    name: "Electronic Components",
    slug: "electronics",
    description: "Semiconductors, PCBs, and electronic modules",
    imageUrl: "/product-4.jpg",
  }
];

export const demoProducts = [
  // Electrical Components
  {
    id: "prod-1",
    name: "Smart WiFi Switch with Energy Monitoring",
    slug: "smart-wifi-switch-energy",
    description: "Advanced smart switch with real-time energy monitoring, remote control via smartphone app, and voice assistant compatibility. Features scheduling, timer functions, and energy usage analytics.",
    shortDescription: "Smart switch with energy monitoring and app control",
    price: 2499,
    originalPrice: 3299,
    imageUrls: JSON.stringify(["/product-1.jpg", "/product-2.jpg", "/product-3.jpg"]),
    brand: "TechFlow",
    model: "TF-SW-001",
    sku: "TFS001",
    stock: 156,
    isActive: true,
    isFeatured: true,
    colors: JSON.stringify(["White", "Black", "Gray"]),
    sizes: JSON.stringify(["Standard"]),
    specifications: JSON.stringify({
      "Power Rating": "10A, 250V AC",
      "Connectivity": "WiFi 802.11 b/g/n",
      "App Support": "iOS & Android",
      "Voice Control": "Alexa, Google Assistant",
      "Installation": "Standard switch box"
    }),
    warranty: "2 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["smart", "wifi", "energy-monitoring", "automation"]),
    views: 2840,
    salesCount: 1205,
    rating: 4.8,
    reviewCount: 342,
    categoryId: "cat-electrical",
    sellerId: "seller-1"
  },
  {
    id: "prod-2", 
    name: "Premium MCB 32A Single Pole Circuit Breaker",
    slug: "premium-mcb-32a-single-pole",
    description: "High-quality miniature circuit breaker with superior breaking capacity and reliable protection. Tested for 10,000+ operations with quick trip mechanism.",
    shortDescription: "Premium 32A single pole MCB with reliable protection",
    price: 899,
    imageUrls: JSON.stringify(["/product-2.jpg", "/product-1.jpg"]),
    brand: "SafeGuard",
    model: "SG-MCB-32A",
    sku: "SGM32A",
    stock: 890,
    isActive: true,
    isFeatured: true,
    colors: JSON.stringify(["White"]),
    sizes: JSON.stringify(["Standard"]),
    specifications: JSON.stringify({
      "Current Rating": "32A",
      "Voltage": "230/400V AC",
      "Breaking Capacity": "6kA",
      "Poles": "Single Pole",
      "Standard": "IS/IEC 60898"
    }),
    warranty: "5 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns", 
    tags: JSON.stringify(["mcb", "circuit-breaker", "protection", "electrical"]),
    views: 5670,
    salesCount: 15670,
    rating: 4.9,
    reviewCount: 2340,
    categoryId: "cat-electrical",
    sellerId: "seller-2"
  },

  // Lighting Solutions
  {
    id: "prod-3",
    name: "Industrial LED High Bay Light 150W",
    slug: "industrial-led-high-bay-150w",
    description: "High-performance LED high bay light designed for warehouses, factories, and industrial spaces. Energy-efficient with superior light distribution and long lifespan.",
    shortDescription: "150W industrial LED high bay light for warehouses",
    price: 8999,
    imageUrls: JSON.stringify(["/product-3.jpg", "/product-4.jpg"]),
    brand: "LuminTech",
    model: "LT-HB-150",
    sku: "LTH150",
    stock: 45,
    isActive: true,
    isFeatured: true,
    colors: JSON.stringify(["Black", "Gray"]),
    sizes: JSON.stringify(["150W"]),
    specifications: JSON.stringify({
      "Power": "150W",
      "Lumens": "22,500 lm",
      "Color Temperature": "5000K Daylight",
      "Beam Angle": "120°",
      "Mounting Height": "6-15 meters",
      "IP Rating": "IP65"
    }),
    warranty: "5 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["led", "high-bay", "industrial", "energy-efficient"]),
    views: 1230,
    salesCount: 890,
    rating: 4.6,
    reviewCount: 128,
    categoryId: "cat-lighting",
    sellerId: "seller-3"
  },
  {
    id: "prod-4",
    name: "LED Panel Light 40W Ultra Slim",
    slug: "led-panel-light-40w-ultra-slim",
    description: "Ultra-slim LED panel light perfect for offices, hospitals, and commercial spaces. Uniform light distribution with flicker-free operation.",
    shortDescription: "40W ultra-slim LED panel for commercial spaces",
    price: 2199,
    imageUrls: JSON.stringify(["/product-4.jpg", "/product-1.jpg"]),
    brand: "SlimLight",
    model: "SL-PL-40",
    sku: "SLP40",
    stock: 234,
    isActive: true,
    isFeatured: false,
    colors: JSON.stringify(["White"]),
    sizes: JSON.stringify(["600x600mm", "600x300mm"]),
    specifications: JSON.stringify({
      "Power": "40W",
      "Lumens": "4800 lm",
      "Color Temperature": "4000K-6500K",
      "Thickness": "12mm",
      "CRI": ">80",
      "Lifespan": "50,000 hours"
    }),
    warranty: "3 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["led", "panel", "slim", "commercial"]),
    views: 3450,
    salesCount: 12340,
    rating: 4.8,
    reviewCount: 1890,
    categoryId: "cat-lighting",
    sellerId: "seller-4"
  },

  // Tools & Equipment
  {
    id: "prod-5",
    name: "Digital Multimeter Professional Grade",
    slug: "digital-multimeter-professional",
    description: "Professional digital multimeter with high accuracy measurements, auto-ranging, and advanced safety features. Perfect for electrical professionals and technicians.",
    shortDescription: "Professional digital multimeter with auto-ranging",
    price: 5499,
    originalPrice: 6999,
    imageUrls: JSON.stringify(["/product-1.jpg", "/product-2.jpg"]),
    brand: "MeterPro",
    model: "MP-DMM-600",
    sku: "MPD600",
    stock: 78,
    isActive: true,
    isFeatured: true,
    colors: JSON.stringify(["Yellow", "Red"]),
    sizes: JSON.stringify(["Standard"]),
    specifications: JSON.stringify({
      "DC Voltage": "0.1mV to 1000V",
      "AC Voltage": "0.1mV to 750V", 
      "DC Current": "0.1µA to 10A",
      "Resistance": "0.1Ω to 40MΩ",
      "Display": "6000 count LCD",
      "Safety": "CAT III 1000V, CAT IV 600V"
    }),
    warranty: "3 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["multimeter", "testing", "professional", "measurement"]),
    views: 2100,
    salesCount: 2156,
    rating: 4.9,
    reviewCount: 567,
    categoryId: "cat-tools",
    sellerId: "seller-5"
  },
  {
    id: "prod-6",
    name: "Digital Clamp Meter AC/DC True RMS",
    slug: "digital-clamp-meter-ac-dc",
    description: "Professional clamp meter for measuring AC/DC current without breaking the circuit. Features True RMS measurement and data logging capabilities.",
    shortDescription: "AC/DC clamp meter with True RMS measurement",
    price: 3299,
    imageUrls: JSON.stringify(["/product-2.jpg", "/product-3.jpg"]),
    brand: "ClampTech",
    model: "CT-CM-400",
    sku: "CTC400",
    stock: 67,
    isActive: true,
    isFeatured: false,
    colors: JSON.stringify(["Black", "Red"]),
    sizes: JSON.stringify(["Standard"]),
    specifications: JSON.stringify({
      "AC Current": "0.1A to 400A",
      "DC Current": "0.1A to 400A",
      "Voltage": "0.1V to 600V",
      "Jaw Opening": "30mm",
      "True RMS": "Yes",
      "Data Logging": "2000 records"
    }),
    warranty: "2 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["clamp-meter", "current", "testing", "true-rms"]),
    views: 1890,
    salesCount: 9870,
    rating: 4.9,
    reviewCount: 1567,
    categoryId: "cat-tools",
    sellerId: "seller-6"
  },

  // Industrial Equipment  
  {
    id: "prod-7",
    name: "3-Phase Motor Protection Relay",
    slug: "3-phase-motor-protection-relay",
    description: "Advanced motor protection relay with comprehensive protection features including over-current, under-voltage, phase failure, and temperature monitoring.",
    shortDescription: "3-phase motor protection relay with comprehensive protection",
    price: 12999,
    imageUrls: JSON.stringify(["/product-3.jpg", "/product-4.jpg"]),
    brand: "GuardTech",
    model: "GT-MPR-300",
    sku: "GTM300",
    stock: 23,
    isActive: true,
    isFeatured: false,
    colors: JSON.stringify(["Black"]),
    sizes: JSON.stringify(["Standard"]),
    specifications: JSON.stringify({
      "Voltage Range": "300-500V AC",
      "Current Range": "0.1-100A",
      "Protection": "Over/Under Current, Voltage, Phase",
      "Display": "LCD with backlight",
      "Communication": "Modbus RTU",
      "Mounting": "DIN Rail"
    }),
    warranty: "3 years manufacturer warranty", 
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["motor", "protection", "relay", "industrial"]),
    views: 890,
    salesCount: 456,
    rating: 4.7,
    reviewCount: 89,
    categoryId: "cat-industrial",
    sellerId: "seller-7"
  },
  {
    id: "prod-8",
    name: "Variable Frequency Drive 1HP",
    slug: "variable-frequency-drive-1hp",
    description: "Single phase to three phase VFD for precise motor speed control with energy savings and soft start/stop functionality.",
    shortDescription: "1HP VFD for precise motor speed control",
    price: 25999,
    imageUrls: JSON.stringify(["/product-4.jpg", "/product-1.jpg"]),
    brand: "DriveMax",
    model: "DM-VFD-1HP",
    sku: "DMV1HP",
    stock: 15,
    isActive: true,
    isFeatured: false,
    colors: JSON.stringify(["Black"]),
    sizes: JSON.stringify(["1HP"]),
    specifications: JSON.stringify({
      "Input": "Single Phase 230V",
      "Output": "Three Phase 230V",
      "Power": "0.75kW/1HP",
      "Frequency": "0-400Hz",
      "Control": "V/F, Sensorless Vector",
      "Protection": "IP20"
    }),
    warranty: "2 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["vfd", "motor-control", "energy-saving", "industrial"]),
    views: 1245,
    salesCount: 3450,
    rating: 4.7,
    reviewCount: 890,
    categoryId: "cat-industrial",
    sellerId: "seller-8"
  },

  // Automation Systems
  {
    id: "prod-9",
    name: "IoT-Enabled Circuit Breaker",
    slug: "iot-circuit-breaker",
    description: "Next-generation smart circuit breaker with IoT connectivity, remote monitoring, and predictive maintenance capabilities.",
    shortDescription: "Smart IoT circuit breaker with remote monitoring",
    price: 15999,
    imageUrls: JSON.stringify(["/product-1.jpg", "/product-2.jpg"]),
    brand: "SmartGrid",
    model: "SG-IoT-CB",
    sku: "SGIOT",
    stock: 34,
    isActive: true,
    isFeatured: true,
    colors: JSON.stringify(["Black", "White"]),
    sizes: JSON.stringify(["Standard"]),
    specifications: JSON.stringify({
      "Current Rating": "16A-63A",
      "Connectivity": "WiFi, 4G LTE",
      "Monitoring": "Current, Voltage, Power, Energy",
      "Features": "Remote Control, Scheduling",
      "App": "iOS & Android",
      "Cloud": "AWS IoT Core"
    }),
    warranty: "3 years manufacturer warranty",
    returnPolicy: "30-day hassle-free returns",
    tags: JSON.stringify(["iot", "smart", "circuit-breaker", "monitoring"]),
    views: 1205,
    salesCount: 234,
    rating: 4.5,
    reviewCount: 23,
    categoryId: "cat-automation",
    sellerId: "seller-9"
  },
  {
    id: "prod-10",
    name: "Wireless Power Quality Analyzer",
    slug: "wireless-power-quality-analyzer",
    description: "Advanced wireless power quality analyzer for monitoring electrical parameters, harmonic analysis, and power system diagnostics.",
    shortDescription: "Wireless power quality analyzer with harmonic analysis",
    price: 45999,
    imageUrls: JSON.stringify(["/product-2.jpg", "/product-3.jpg"]),
    brand: "AnalyzePro",
    model: "AP-PQA-Wireless",
    sku: "APPQA",
    stock: 8,
    isActive: true,
    isFeatured: false,
    colors: JSON.stringify(["Black"]),
    sizes: JSON.stringify(["Portable"]),
    specifications: JSON.stringify({
      "Channels": "4 Voltage + 4 Current",
      "Accuracy": "±0.1%",
      "Sampling Rate": "256 samples/cycle",
      "Harmonics": "Up to 50th order",
      "Connectivity": "WiFi, Bluetooth",
      "Battery": "8 hours continuous"
    }),
    warranty: "2 years manufacturer warranty",
    returnPolicy: "15-day hassle-free returns",
    tags: JSON.stringify(["power-quality", "analyzer", "wireless", "harmonics"]),
    views: 567,
    salesCount: 89,
    rating: 4.8,
    reviewCount: 12,
    categoryId: "cat-automation",
    sellerId: "seller-10"
  }
];

export const demoSellers = [
  {
    id: "seller-1",
    name: "TechFlow Solutions",
    email: "contact@techflow.com",
    password: "hashedpassword",
    avatar: null,
    bio: "Leading provider of smart electrical solutions",
    location: "Mumbai, Maharashtra",
    phone: "+91 98765 43210",
    isVerified: true,
    tier: "Gold",
    totalSales: 125000,
    totalOrders: 450,
    rating: 4.8
  },
  {
    id: "seller-2", 
    name: "SafeGuard Industries",
    email: "sales@safeguard.com",
    password: "hashedpassword",
    avatar: null,
    bio: "Trusted manufacturer of electrical protection devices",
    location: "Delhi, India",
    phone: "+91 98765 43211",
    isVerified: true,
    tier: "Platinum",
    totalSales: 850000,
    totalOrders: 2340,
    rating: 4.9
  },
  // Add more sellers...
];

export const demoReviews = [
  {
    id: "review-1",
    rating: 5,
    title: "Excellent smart switch!",
    comment: "Works perfectly with my smart home setup. The energy monitoring feature is very useful and the app is intuitive.",
    images: null,
    isVerified: true,
    helpfulCount: 23,
    productId: "prod-1",
    userId: "user-1"
  },
  {
    id: "review-2",
    rating: 4,
    title: "Reliable circuit breaker",
    comment: "Good quality MCB, installed 10 of these in my new house. Working great so far.",
    images: null,
    isVerified: true,
    helpfulCount: 15,
    productId: "prod-2", 
    userId: "user-2"
  },
  // Add more reviews...
];

